package com.geometry.geometry.cutting;

import com.geometry.core.mesh.Mesh;
import com.geometry.geometry.analysis.Section;
import com.geometry.geometry.operation.OperationResult;

/**
 * Phase 08 - Complete result of a mesh cut operation.
 *
 * Extends OperationResult with section analysis data.
 * Contains the cut meshes plus the cross-section polygon
 * that was generated by the cut.
 */
public class CutResult {

    private final OperationResult operationResult;
    private final Section section;

    /**
     * Create a cut result.
     *
     * @param operationResult the result from the geometry operation
     * @param section         the cross-section produced by the cut (may be null)
     */
    public CutResult(OperationResult operationResult, Section section) {
        if (operationResult == null) {
            throw new IllegalArgumentException("OperationResult cannot be null");
        }
        this.operationResult = operationResult;
        this.section = section;
    }

    /**
     * Return the operation result (meshes and success status).
     */
    public OperationResult getOperationResult() {
        return operationResult;
    }

    /**
     * Return the output meshes.
     */
    public Mesh[] getMeshes() {
        return operationResult.getMeshes().toArray(new Mesh[0]);
    }

    /**
     * Return the first output mesh.
     */
    public Mesh getMesh() {
        return operationResult.getMesh();
    }

    /**
     * Return the number of output meshes.
     */
    public int getMeshCount() {
        return operationResult.getMeshCount();
    }

    /**
     * Return the cross-section polygon, or null if not available.
     */
    public Section getSection() {
        return section;
    }

    /**
     * Check if the cut was successful.
     */
    public boolean isSuccess() {
        return operationResult.isSuccess();
    }

    /**
     * Return a message describing the result.
     */
    public String getMessage() {
        return operationResult.getMessage();
    }

    @Override
    public String toString() {
        return "CutResult{success=" + isSuccess() + ", meshes=" + getMeshCount()
                + ", section=" + (section != null ? section.pointCount() + " points" : "none") + "}";
    }
}
